# Should match the version used in production
FROM nginx:1.29@sha256:9dd288848f4495869f76676e419ae2d767ca99fece2ec37ec0261f9fdaab5204

RUN apt-get -q update \
    && apt-get -q --yes install ncat \
    && apt-get clean
